version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: prueba_inventario
      POSTGRES_USER: edu
      POSTGRES_PASSWORD: edu
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data